-- alter table books add column deleted boolean default false
create table authors
(
    id         bigint generated by default as identity not null,
    created_at timestamp without time zone             not null,
    updated_at timestamp without time zone             not null,
    name       varchar(255),
    surname    varchar(255),
    country_id bigint,
    constraint pk_authors primary key (id)
);

create table books
(
    id               bigint generated by default as identity not null,
    created_at       timestamp without time zone             not null,
    updated_at       timestamp without time zone             not null,
    name             varchar(255)                            not null,
    category_id      bigint                                  not null,
    state_id         bigint                                  not null,
    available_copies integer,
    constraint pk_books primary key (id)
);

create table books_authors
(
    id         bigint generated by default as identity not null,
    book_id    bigint not null,
    author_id  bigint not null
);

create table categories
(
    id          bigint generated by default as identity not null,
    name        varchar(255)                            not null,
    description varchar(255),
    constraint pk_categories primary key (id)
);

create table countries
(
    id        bigint generated by default as identity not null,
    name      varchar(255)                            not null,
    continent varchar(255)                            not null,
    constraint pk_countries primary key (id)
);

create table states
(
    id    bigint generated by default as identity not null,
    state varchar(255),
    constraint pk_states primary key (id)
);

alter table categories
    add constraint uc_categories_name unique (name);

alter table authors
    add constraint fk_authors_on_country foreign key (country_id) references countries (id);

alter table books
    add constraint fk_books_on_category foreign key (category_id) references categories (id);

alter table books
    add constraint fk_books_on_state foreign key (state_id) references states (id);

alter table books_authors
    add constraint fk_booaut_on_author foreign key (author_id) references authors (id);

alter table books_authors
    add constraint fk_booaut_on_book foreign key (book_id) references books (id);